### ISSUE TITLE
Data size no match with Raspberry Pi pico

### ISSUE THREAD

**Issue by WotoAOT** [xreef/EByte_LoRa_E220_micropython_library#3]
Hello,

I have connected the E220-900T22D module to the Raspberry Pi pico as follows:
Pico ----- E220
1 -------- 4 (TxD)
2 -------- 3 (RxD)
15 ------- 5 (AUX)
21 ------- 1 (M0)
19 ------- 2 (M1)

I use the UART0 on the Pico (pin 1 and 2). I have also connected a 4.7kOhm pull-up resistor to each of TxD, RxD and AUX.

Unfortunately, I always get the following message:

Initialisation: {} Success
Retrieve configuration: {} Data size not match!
----------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 29, in <module>
  File "/lib/LoraWanE220/lora_e220.py", line 245, in print_configuration
AttributeError: 'NoneType' object has no attribute '_COMMAND'

What could be the reason?

best regards
Woto

**Comment by xreef** [comment]
Hi,
Normally we get that error when the wiring isn't correct.
Try to check it.
Bye Renzo

**Comment by xreef** [comment]
You can try to follow the schema of e32 with pico
https://mischianti.org/ebyte-lora-e32-micropython-exploring-library-2/
Bye Renzo

**Comment by WotoAOT** [comment]
Hello Renzo,
Thank you very much. It works now.
So that I can use 868Mhz, I have to change the value from 23 to 18 in the lib lora_e220.py line 165, is that correct?
Or is there a command for this?

best regards,
Woto

**Comment by WotoAOT** [comment]
I have set the line to
self.CHAN = 18
but the frequency is still 873 Mhz.

**Comment by xreef** [comment]
Can you open a forum topic with the code you use please?
Thanks Renzo

**Comment by WotoAOT** [comment]
Hello Renzo,
Yes, but I'm new here and don't know how to create a forum topic.
Here is my code:

from machine import UART

from LoraWanE220.lora_e220 import LoRaE220, print_configuration
from LoraWanE220.lora_e220_operation_constant import ResponseStatusCode

uart1 = UART(1)

lora = LoRaE220('900T22D', uart1, aux_pin=2, m0_pin=10, m1_pin=11)

code = lora.begin()
print("Initialisation: {}", ResponseStatusCode.get_description(code))

code, configuration = lora.get_configuration()

print("Retrieve configuration: {}", ResponseStatusCode.get_description(code))

print_configuration(configuration)

**Comment by WotoAOT** [comment]
Hello Renzo,

i have opened a new topic in the forum.
I think that setting the channel is not implemented in the library.

Best regards
Woto

**Comment by xreef** [comment]
https://mischianti.org/forums/topic/data-size-no-match-with-raspberry-pi-pico/#post-29077
