### ISSUE TITLE
How do 3 ebytes work together?

### ISSUE THREAD

**Issue by aspartech** [xreef/EByte_LoRa_E220_micropython_library#4]
Hello, I need to use 3 ebytes for a project and 1 ebyte must communicate with all of them. Also, the data needs to go every 1 second. We communicated 2 ebytes with a loop, but it worked very slowly and we could not add the 3rd ebyte. Thanks in advance.

**Comment by xreef** [comment]
https://github.com/xreef/EByte_LoRa_E32_circuitpython_library/issues/1#issuecomment-1988884987
