### ISSUE TITLE
uart: tout_thresh = 244 > maximum value = 101

### ISSUE THREAD

**Issue by manuf3006** [xreef/EByte_LoRa_E220_micropython_library#5]
Hey everyone, 

I am trying to set up a communication between two esp32 (WROOM-32) with a EBYTE E220-900T22D. 
The ESP is flashed with Micropython 1.21.0 (I also tried 1.22.0) and I did the wiring as described by xreef. 

Until now I wasn't able to set up any communication. 
Currently I get the following error (sender and receiver): 

_uart: tout_thresh = 244 > maximum value = 101
Initialization: {} Success
Set configuration: {} Data size not match!
Send message: {} Success_

Even though it tells me 'Success', no message is received at the other ESP. 
I'm using the two examples
* send_fixed_string_message.py
* receive_string_message.py

I'm really hoping someone can help me here. 
Thanks 
M

**Comment by xreef** [comment]
Hi,
first try to retrieve the configuration, the message 
_Set configuration: {} Data size not match!_
say that there is a problem.
Bye Renzo

**Comment by manuf3006** [comment]
Hey Renzo, 
Thank you so much for your help. 
I ran your script 'get_configuration.py' ([HERE](https://github.com/xreef/EByte_LoRa_E220_micropython_library/blob/master/examples/get_configuration.py)) and got the following output: 

_rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4728
load:0x40078000,len:14876
ho 0 tail 12 room 4
load:0x40080400,len:3368
entry 0x400805cc
E (860) uart: tout_thresh = 244 > maximum value = 101
Initialization: {} Success
Retrieve configuration: {} Data size not match!
----------------------------------------
Traceback (most recent call last):
  File "main.py", line 39, in <module>
  File "lora_e220.py", line 245, in print_configuration
AttributeError: 'NoneType' object has no attribute '_COMMAND'
MicroPython v1.21.0 on 2023-10-05; Generic ESP32 module with ESP32_

Thank you again for your Help. 
Manuel

**Comment by xreef** [comment]
Hi Manuel,
ah, ok, It's a wiring problem, It can't retrieve the data.
Bye Renzo

**Comment by manuf3006** [comment]
Hey Renzo, 

Okay, that is very very strange. I checked the wiring 5 times. I use this Dev Board Pinout [HERE](https://cdn.shopify.com/s/files/1/1509/1638/files/ESP-32_NodeMCU_Developmentboard_Pinout.pdf?v=1609851295)
I've connected 
- GPIO17 (U2TXD) with the E220 TXD
- GPIO16 (U2RXD) with the E220 RXD
I use the 5V and GND from the DEV Board to supply the E220. 
The E220 AUX is floating (which should be no problem. I also tried Pull-Up) 
And M0 and M1 are on GND (I also tried other wirings here) 

There is actualy not really much to make wrong. At least I thought so :)
Manuel

**Comment by xreef** [comment]
Hi,
Ahh! Okay, you must put 3.3v in M0 and M1.
Use this article for reference 
https://mischianti.org/ebyte-lora-e220-llcc68-device-for-arduino-esp32-or-esp8266-configuration-3/
https://mischianti.org/nodemcu-v3-high-resolution-pinout-and-specs/

Bye Renzo

**Comment by manuf3006** [comment]
Hey Renzo, 
Thank you again for your help. 
Unfortunately that didn't help either. As I mentioned above, I tried different wiring for M0 and M1. GND, 3.3V and 5V. 
I'm really stuck here. 

BR
Manuel

**Comment by manuf3006** [comment]
Hey Renzo, 
i found my problem. I mixed RX and TX. 
I've connected
* GPIO17 (U2TXD) with the E220 TXD
* GPIO16 (U2RXD) with the E220 RXD

But it should be the other way round (RX to TX and viceversa) 
I still get the uart error, but I get some configuration back: 

> E (920) uart: tout_thresh = 244 > maximum value = 101
->  Disabled (default)

> TransModeWORPeriod :  0b11  ->  2000ms (default)
> TransModeEnableLBT :  0b0  ->  Disabled (default)
> TransModeEnableRSSI:  0b1  ->  Enabled
> TransModeFixedTrans:  0b1  ->  Fixed transmission (first three bytes can be used as high/low address and channel)


Can I ignore the error?
